
services:
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    labels:
      - "prometheus_job=nginx"
    networks:
      - monitoring
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      retries: 3

  # Nginx Exporter (sidecar)
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-prometheus-exporter
    ports:
      - "9113:9113"
    networks:
      - monitoring
    depends_on:
      - nginx
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'

 
  # Python Flask service
  flask:
    build: ./flask-app
    container_name: flask
    ports:
      - "5000:5000"
    labels:
      - "prometheus_job=flask"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      retries: 3

  # Prometheus Server
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  # Grafana Server
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
