global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'apache'
    static_configs:
      - targets: ['apache:80']

  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5000']
